name: flame_behaviors
description: Flame Behaviors applies separation of concerns to game logic in the form of Entities and Behaviors, built by Very Good Ventures.
version: 0.2.0
homepage: https://github.com/VeryGoodOpenSource/flame_behaviors
repository: https://github.com/VeryGoodOpenSource/flame_behaviors
issue_tracker: https://github.com/VeryGoodOpenSource/flame_behaviors/issues
documentation: https://github.com/VeryGoodOpenSource/flame_behaviors/tree/main/docs

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ">=1.6.0 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.9.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
